### PR TITLE
Fix another empty container error

### PR DESCRIPTION
**Pull request by kristapsPelna**
As a followup of https://github.com/eBayClassifiedsGroup/react-advertising/pull/73
There is another case where the unobserve can be called with an empty object causing an error:
`Argument 1 ('target') to IntersectionObserver.unobserve must be an instance of Element`

### CODE REVIEW

**Review by sundy001 — APPROVED** [review]
LGTM

**Comment by salami-art** [comment]
When is this going to be released on NPM?

**Comment by JavierMartinz** [comment]
I was going to submit a PR, because I also had this error in my project but I saw it was already fixed. Can you please release it? 🙏  thanks!

**Comment by juanpicado** [comment]
I will ask tomorrow at work how we can do it.

**Comment by pahund** [comment]
I've released version 4.1.1, which contains the fix. 

Thank you @salami-art and @JavierMartinz for your patience, let me know if I can help you further.

**Pull request merged**
